---
services:
  redis-db:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: ["--save", "1", "1"]

  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: vigneshwinner/gene_api:1.0
    ports:
      - "5000:5000"
    environment:
      - REDIS_IP=redis-db
      - REDIS_PORT=6379

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: vigneshwinner/gene_api:1.0
    environment:
      - REDIS_IP=redis-db
      - REDIS_PORT=6379
    command: ["src/worker.py"]
